/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xgestion;

import com.xgestion2.repository.UsuarioRepository;
import com.xgestion2.vistas.ajustes.FormMiEmpresaLicencia;
import javax.swing.JOptionPane;

/**
 *
 * @author dario
 */
public class FormLogin extends javax.swing.JDialog {

    /**
     * Creates new form FormLogin
     */
    public FormLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        textUsuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        botonOk = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonLicencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(250, 250, 460, 300));
        setModal(true);
        setUndecorated(true);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/candado1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 136, 140));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("PASSWORD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 119, 37));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 119, 37));

        textUsuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        textUsuario.setNextFocusableComponent(textPassword);
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 196, 35));

        textPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        textPassword.setNextFocusableComponent(botonOk);
        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 196, 37));

        botonOk.setBackground(new java.awt.Color(153, 153, 153));
        botonOk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonOk.setMnemonic('I');
        botonOk.setText("INGRESAR");
        botonOk.setNextFocusableComponent(botonCancelar);
        botonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOkActionPerformed(evt);
            }
        });
        getContentPane().add(botonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 140, 52));

        botonCancelar.setBackground(new java.awt.Color(153, 153, 153));
        botonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonCancelar.setMnemonic('C');
        botonCancelar.setText("CANCELAR");
        botonCancelar.setNextFocusableComponent(botonLicencia);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, 52));

        botonLicencia.setBackground(new java.awt.Color(102, 102, 102));
        botonLicencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonLicencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Llave.png"))); // NOI18N
        botonLicencia.setNextFocusableComponent(textUsuario);
        botonLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLicenciaActionPerformed(evt);
            }
        });
        getContentPane().add(botonLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 40));

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(458, 216));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOkActionPerformed
        // TODO add your handling code here:
        UsuarioRepository usuario = new UsuarioRepository();
        if(usuario.isUsuarioPasswordValido(textUsuario.getText(), textPassword.getText())){
            FormPrincipal.miUsuario = usuario.getUsuario(textUsuario.getText(), textPassword.getText());
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Usuario Inválido.");
            textPassword.setText("");
            textUsuario.setText("");
            textUsuario.requestFocus();
        }
    }//GEN-LAST:event_botonOkActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
        textPassword.requestFocus();
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        // TODO add your handling code here:
        botonOk.doClick();
    }//GEN-LAST:event_textPasswordActionPerformed

    private void botonLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLicenciaActionPerformed
        // TODO add your handling code here:
        FormMiEmpresaLicencia cm = new FormMiEmpresaLicencia(null,true,Long.valueOf(0));
        cm.setVisible(true);
    }//GEN-LAST:event_botonLicenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonLicencia;
    private javax.swing.JButton botonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
