/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xgestion;

import com.vistas.ventas.FormBalanceCaja;
import com.vistas.ventas.FormVenta;
import com.vistas.ventas.FormVentas;
import com.xgestion.vista.mercaderia.FormListadoStock;
import com.xgestion.vista.mercaderia.FormOrdenesCompras;
import com.xgestion2.entities.maestros.Computadora;
import com.xgestion2.entities.maestros.Config;
import com.xgestion2.entities.maestros.Empresa;
import com.xgestion2.entities.maestros.Sucursal;
import com.xgestion2.entities.maestros.Turno;
import com.xgestion2.entities.maestros.Usuario;
import com.xgestion2.manager.SessionFactoryManager;
import com.xgestion2.repository.ComputadoraRepository;
import com.xgestion2.repository.EmpresaRepository;
import com.xgestion2.repository.SucursalRepository;
import com.xgestion2.repository.TurnoRepository;
import com.xgestion2.util.Encriptador;
import com.xgestion2.vistas.ajustes.FormClientes;
import com.xgestion2.vistas.ajustes.FormFamilias;
import com.xgestion2.vistas.ajustes.FormMiEmpresa;
import com.xgestion2.vistas.ajustes.FormProductos;
import com.xgestion2.vistas.ajustes.FormProveedores;
import com.xgestion2.vistas.ajustes.FormSubfamilias;
import com.xgestion2.vistas.ajustes.FormTurnos;
import com.xgestion2.vistas.ajustes.FormUbicaciones;
import com.xgestion2.vistas.ajustes.FormUmes;
import com.xgestion2.vistas.ajustes.FormUsuarios;
import com.xgestion2.vistas.finanzas.FormListadoPrecios;
import com.xgestion2.vistas.finanzas.FormOfertas;
import com.xgestion2.vistas.finanzas.FormPagos;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Properties;
import javax.imageio.ImageIO;
import org.apache.log4j.Logger;
import org.hibernate.SessionFactory;
import org.imgscalr.Scalr;

/**
 *
 * @author dario
 */
public class FormPrincipal extends javax.swing.JFrame {

    private static SessionFactoryManager manager;
    public static SessionFactory sessionFactory;
    public static Properties prop;
    private BufferedImageOp[] ops;
    private Image i;
    public static Logger logger = Logger.getLogger(FormPrincipal.class);
    public static Encriptador encriptador = new Encriptador();
    
    private EmpresaRepository empresaRepo = new EmpresaRepository();
    private SucursalRepository sucursalRepo = new SucursalRepository();
    private ComputadoraRepository computadoraRepo = new ComputadoraRepository();
    private TurnoRepository turnoRepo = new TurnoRepository();
    
    public static Empresa miEmpresa = new Empresa();
    public static Sucursal miSucursal = new Sucursal();
    public static Computadora miComputadora = new Computadora();
    public static Usuario miUsuario = new Usuario();
    public static Turno miTurno = new Turno();
    
    /**
     * Creates new form Principal
     */
    public FormPrincipal() {
        try {
            prop = new Config().getPropValues();                   
            manager = new SessionFactoryManager();
            sessionFactory = manager.getSessionFactory();
            
            if(Boolean.valueOf(prop.getProperty("iniciarPorPimeraVez"))){
                incioPorPrimeraVez();
             }
            
            FormLogin login = new FormLogin(this,true);
            login.setVisible(true);

            i = ImageIO.read(getClass().getResource("/com/util/images/icon.png"));

            try {
                miTurno         = turnoRepo.getTurnoActual();
                miEmpresa       = empresaRepo.get(Long.valueOf(Encriptador.Desencriptar(prop.getProperty("miEmpresa"))));
                miSucursal      = sucursalRepo.get(Long.valueOf(Encriptador.Desencriptar(prop.getProperty("miSucursal"))));
                miComputadora   = computadoraRepo.get(Long.valueOf(Encriptador.Desencriptar(prop.getProperty("miComputadora"))));     
            } catch (Exception ex) {
                logger.error("Error al cargar datos primarios: ",ex);
            }
            initComponents();
            
        } catch (IOException ex) {
            logger.error("Error: ", ex);
            System.exit(0);
        }
        
        repaint();
        revalidate();
        
    }
    
    public void incioPorPrimeraVez(){
        PrimeraEjecucion primera = new PrimeraEjecucion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        desktop = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelEmpresa = new javax.swing.JLabel();
        jLabelSucursal = new javax.swing.JLabel();
        jLabelComputadora = new javax.swing.JLabel();
        jLabelUsuario1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelUsuario2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XGESTION 2.0.0");
        setBackground(new java.awt.Color(153, 204, 255));
        setIconImage(this.i);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Monitor2.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Mundo4.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Usuario5.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Inicio5.png"))); // NOI18N

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText(miUsuario.getNombre());

        jLabelEmpresa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmpresa.setText(miEmpresa.getNombre());

        jLabelSucursal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelSucursal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSucursal.setText(miSucursal.getNombre());

        jLabelComputadora.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelComputadora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComputadora.setText(miComputadora.getNombre());

        jLabelUsuario1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario1.setText(miUsuario.getNombre());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Usuario5.png"))); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Reloj.png"))); // NOI18N

        jLabelUsuario2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario2.setText(miTurno.getNombre());

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/background.png"))); // NOI18N
        jLabelFondo.setAlignmentY(0.0F);
        jLabelFondo.setMinimumSize(desktop.size());

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabelUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelEmpresa))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelSucursal))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelComputadora))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabelUsuario1)))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelUsuario2))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        desktop.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabelUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabelEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabelSucursal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabelComputadora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabelUsuario1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabelUsuario2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabelFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Reloj.png"))); // NOI18N
        jMenu1.setText("Ventas");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Moneda.png"))); // NOI18N
        jMenuItem9.setText("Nueva Venta");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Dinero.png"))); // NOI18N
        jMenuItem10.setText("Ventas");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35HojaAmarilla.png"))); // NOI18N
        jMenuItem11.setText("Balance Caja");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Dinero.png"))); // NOI18N
        jMenu4.setText("Finanzas");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Informe3.png"))); // NOI18N
        jMenuItem12.setText("Listado de Precios");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Ofertas.png"))); // NOI18N
        jMenuItem14.setText("Ofertas");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItem15.setText("Modifica en Masa");
        jMenu4.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Centavo.png"))); // NOI18N
        jMenuItem16.setText("Tipos Pago");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Caja.png"))); // NOI18N
        jMenu5.setText("Productos");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Caja.png"))); // NOI18N
        jMenuItem13.setText("Lista Stocks");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Caja.png"))); // NOI18N
        jMenuItem17.setText("O. de Compras");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuBar1.add(jMenu5);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Estadiistica3.png"))); // NOI18N
        jMenu3.setText("Informes");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        jMenu6.setText("Productos");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenu3.add(jMenu6);

        jMenu7.setText("Ventas");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenu3.add(jMenu7);

        jMenu8.setText("Finanzas");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenu3.add(jMenu8);

        jMenu9.setText("Sistema");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenu3.add(jMenu9);

        jMenuBar1.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35LlaveInglesa.png"))); // NOI18N
        jMenu2.setText("Ajustes");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem21.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Usuario13.png"))); // NOI18N
        jMenuItem21.setText("Clientes");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem21);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Caja.png"))); // NOI18N
        jMenu10.setText("Productos");
        jMenu10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jMenuItem22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Usuario10.png"))); // NOI18N
        jMenuItem22.setText("Proveedores");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem22);

        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Red.png"))); // NOI18N
        jMenuItem8.setText("U. Medidas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem8);

        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Red.png"))); // NOI18N
        jMenuItem7.setText("Ubicaciones");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem7);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Red.png"))); // NOI18N
        jMenuItem3.setText("Familias");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Red.png"))); // NOI18N
        jMenuItem4.setText("Subfamilias");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem4);

        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Caja.png"))); // NOI18N
        jMenuItem6.setText("Productos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem6);

        jMenu2.add(jMenu10);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35LlaveInglesa.png"))); // NOI18N
        jMenu11.setText("Ajustes");
        jMenu11.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jMenuItem18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Usuario7.png"))); // NOI18N
        jMenuItem18.setText("Usuarios");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem18);

        jMenuItem19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35LlaveInglesa.png"))); // NOI18N
        jMenuItem19.setText("U. Medidas");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem19);

        jMenuItem23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35LlaveInglesa.png"))); // NOI18N
        jMenuItem23.setText("Turnos");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem23);

        jMenu2.add(jMenu11);

        jMenuItem20.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Informacion.png"))); // NOI18N
        jMenuItem20.setText("Mi Empresa");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem20);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            Toolkit tk = Toolkit.getDefaultToolkit();
            int xSize = ((int) tk.getScreenSize().getWidth());
            int ySize = ((int) tk.getScreenSize().getHeight());
            
            jLabelFondo.setAlignmentX(TOP_ALIGNMENT);
            jLabelFondo.setAlignmentY(TOP_ALIGNMENT);
            jLabelFondo.setSize(xSize, ySize);
            
            File img = new File(getClass().getResource("/com/util/images/background.png").toURI());
            BufferedImage myImage = ImageIO.read(img);
            BufferedImage scaledImage = Scalr.resize(myImage, Scalr.Method.QUALITY, xSize, ySize, ops);
            jLabelFondo.setIcon(new javax.swing.ImageIcon(scaledImage));
            repaint();
                        
        } catch (IOException ex) {
            logger.error("Error: !", ex);
        } catch (URISyntaxException ex) {
           logger.error("Error: !", ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        FormUsuarios x = new FormUsuarios();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }   
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        FormUmes x = new FormUmes();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }    
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        FormMiEmpresa x = new FormMiEmpresa();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }   
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        FormClientes x = new FormClientes();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }   
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        FormProveedores x = new FormProveedores();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FormFamilias x = new FormFamilias();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FormSubfamilias x = new FormSubfamilias();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        FormProductos x = new FormProductos();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        FormUbicaciones x = new FormUbicaciones();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        FormUmes x = new FormUmes();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        FormTurnos x = new FormTurnos();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        FormOfertas x = new FormOfertas();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        FormPagos x = new FormPagos();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        FormVenta x = new FormVenta(null);
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        FormVentas x = new FormVentas();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        FormBalanceCaja x = new FormBalanceCaja(null,true);
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        FormListadoPrecios x = new FormListadoPrecios();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        FormListadoStock x = new FormListadoStock();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        FormOrdenesCompras x = new FormOrdenesCompras();
        desktop.add(x);
        x.pack();
        x.setVisible(true);
        
        try {
            x.setMaximum(true);
        } catch (PropertyVetoException e) {
         logger.error("Error Menu", e);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
           logger.error("Error: !", ex);
        } catch (InstantiationException ex) {
            logger.error("Error: !", ex);
        } catch (IllegalAccessException ex) {
            logger.error("Error: !", ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.error("Error: !", ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelComputadora;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuario1;
    private javax.swing.JLabel jLabelUsuario2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
