/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas.ventas;

import com.xgestion2.vistas.finanzas.*;
import com.xgestion2.vistas.ajustes.*;
import com.xgestion2.entities.maestros.Oferta;
import com.xgestion2.entities.maestros.Proveedor;
import com.xgestion2.entities.maestros.Subfamilia;
import com.xgestion2.entities.maestros.UME;
import com.xgestion2.entities.maestros.Ubicacion;
import com.xgestion2.repository.OfertaRepository;
import com.xgestion2.repository.SubfamiliaRepository;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import xgestion.FormPrincipal;

/**
 *
 * @author dario
 */
public class FormBalanceCaja extends javax.swing.JDialog {

    /**
     * Creates new form FormOferta
     */
    private final OfertaRepository y = new OfertaRepository();
    private Oferta x = new Oferta();
    
    public FormBalanceCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        cargarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textElementoNombre = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox();
        textDescuento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textElemento = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        comboTipo1 = new javax.swing.JComboBox();
        dateFecha = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 600, 400));
        setMinimumSize(new java.awt.Dimension(514, 200));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(490, 340));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("DESCUENTO *:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 137, 37));

        textElementoNombre.setEditable(false);
        textElementoNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(textElementoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 230, 40));

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Informe3.png"))); // NOI18N
        jButtonGuardar.setMnemonic('R');
        jButtonGuardar.setText("REPORTE");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 150, 50));

        comboTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-Producto", "2-Familia", "3-Subfamilia", "4-Ubicacion" }));
        getContentPane().add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 310, 40));

        textDescuento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textDescuento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(textDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 310, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("FECHA *:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 137, 37));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("TURNO *:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 137, 37));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("SUCURSAL *:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 137, 37));

        textElemento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textElemento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(textElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 70, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("TIPO *:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 137, 37));

        comboTipo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboTipo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-Producto", "2-Familia", "3-Subfamilia", "4-Ubicacion" }));
        getContentPane().add(comboTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 310, 40));

        dateFecha.setDate(new java.util.Date());
        dateFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(dateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 310, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
       
//        if(jPasswordField1.getText().equals(jPasswordField2.getText())){
           
            if(!textDescuento.getText().isEmpty() && !dateFecha.getDate().toString().isEmpty() && !textElemento.getText().isEmpty() ){
                    
                
            }else{
                JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios.");
            }
//        }else{
//            JOptionPane.showMessageDialog(null, "Los passwords deben coincidir.");
//        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void cargarValores(){
        
         //SETEO FECHA ACTUAL
//        try {
//            MaskFormatter dateMask = new MaskFormatter("##/##/##");
//            dateMask.install(textDesde);
//        } catch (ParseException ex) {
//            FormPrincipal.logger.error("ERROR: "+ex.toString());
//        }
//        
//        SimpleDateFormat df = new SimpleDateFormat( "dd/MM/yy" );
//        textDesde.setText(df.format( new Date()));
//        
        String nombre = "";
        
//        switch(x.getTipo()){
//            case 1:  nombre = "Producto";
//                     break;
//            case 2:  nombre = "Familia";
//                     break;
//            case 3:  nombre = "Subfamilia";
//                     break;
//            case 4:  nombre = "Ubicacion";
//                     break;
//            default: nombre = "";
//                     break;
//        }
//            
//        comboTipo.setSelectedItem(x.getTipo()+"-"+nombre);
        
        repaint();
        revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JComboBox comboTipo1;
    private org.jdesktop.swingx.JXDatePicker dateFecha;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField textDescuento;
    private javax.swing.JFormattedTextField textElemento;
    private javax.swing.JTextField textElementoNombre;
    // End of variables declaration//GEN-END:variables
}
