/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xgestion2.vistas.finanzas;

import com.xgestion.listas.ListaFamilias;
import com.xgestion.listas.ListaProductos;
import com.xgestion.listas.ListaSubfamilias;
import com.xgestion.listas.ListaUbicaciones;
import com.xgestion2.entities.maestros.Familia;
import com.xgestion2.vistas.ajustes.*;
import com.xgestion2.entities.maestros.Oferta;
import com.xgestion2.entities.maestros.Producto;
import com.xgestion2.entities.maestros.Proveedor;
import com.xgestion2.entities.maestros.Subfamilia;
import com.xgestion2.entities.maestros.UME;
import com.xgestion2.entities.maestros.Ubicacion;
import com.xgestion2.repository.FamiliaRepository;
import com.xgestion2.repository.OfertaRepository;
import com.xgestion2.repository.ProductoRepository;
import com.xgestion2.repository.SubfamiliaRepository;
import com.xgestion2.repository.UbicacionRepository;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author dario
 */
public class FormOferta extends javax.swing.JDialog {

    /**
     * Creates new form FormOferta
     */
    private final Long id;
    private final OfertaRepository y = new OfertaRepository();
    private Oferta x = new Oferta();
    private Producto producto = new Producto();
    private Familia familia = new Familia();
    private Subfamilia subfamilia = new Subfamilia();
    private Ubicacion ubicacion = new Ubicacion();
    
    private ProductoRepository productoRepo = new ProductoRepository();
    private FamiliaRepository familiaRepo = new FamiliaRepository();
    private SubfamiliaRepository subfamiliaRepo = new SubfamiliaRepository();
    private UbicacionRepository ubicacionRepo = new UbicacionRepository();
    
    public FormOferta(java.awt.Frame parent, boolean modal,Long id) {
        super(parent, modal);
        this.id = id;
        
        initComponents();
        
        if(id>0){
            cargarValores();
        }else{
             //SETEO FECHA ACTUAL
            dateDesde.setDate( new Date());
            dateHasta.setDate( new Date());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textElementoNombre = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        textDescuento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textElemento = new javax.swing.JFormattedTextField();
        dateHasta = new org.jdesktop.swingx.JXDatePicker();
        dateDesde = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 600, 400));
        setMinimumSize(new java.awt.Dimension(514, 200));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(500, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("DESCUENTO *:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 137, 37));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 137, 37));

        textElementoNombre.setEditable(false);
        textElementoNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(textElementoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 230, 40));

        textNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 310, 37));

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Guardar6.png"))); // NOI18N
        jButtonGuardar.setMnemonic('G');
        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 150, 50));

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Eliminar3.png"))); // NOI18N
        jButtonEliminar.setMnemonic('E');
        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 150, 50));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/util/images/ico35Cancelar5.png"))); // NOI18N
        jButtonCancelar.setMnemonic('C');
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 160, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("A");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 37));

        comboTipo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-Producto", "2-Familia", "3-Subfamilia", "4-Ubicacion" }));
        comboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoItemStateChanged(evt);
            }
        });
        getContentPane().add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 310, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NOMBRE *:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 137, 37));

        textDescuento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textDescuento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(textDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 310, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("VALIDEZ  DE *:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 137, 37));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("TIPO OFERTA *:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 137, 37));

        textId.setEditable(false);
        textId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 310, 37));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ELEMENTO *:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 137, 37));

        textElemento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textElemento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textElemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textElementoFocusLost(evt);
            }
        });
        textElemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textElementoKeyPressed(evt);
            }
        });
        getContentPane().add(textElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 70, 40));

        dateHasta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(dateHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 140, 40));

        dateDesde.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateDesde.setMaximumSize(new java.awt.Dimension(160, 30));
        dateDesde.setMinimumSize(new java.awt.Dimension(160, 30));
        getContentPane().add(dateDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
      
    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        
        if(id>0){
            int reply = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar este registro?", "Confirma Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                x.setActivo(false);
                y.update(x);
                dispose();
                if(FormOfertas.jButtonBuscar != null)
                    FormOfertas.jButtonBuscar.doClick();
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
       
//        if(jPasswordField1.getText().equals(jPasswordField2.getText())){
           
            if(!textNombre.getText().isEmpty() && !textDescuento.getText().isEmpty() && !dateDesde.getDate().toString().isEmpty() && !textElemento.getText().isEmpty() && 
                    !dateHasta.getDate().toString().isEmpty() && !textElementoNombre.getText().isEmpty()  && !comboTipo.getSelectedItem().toString().isEmpty() ){
                    
                String[] tipo = comboTipo.getSelectedItem().toString().split("-");
                x.setNombre(textNombre.getText());
                x.setDescuento(Integer.valueOf(textDescuento.getText()));
                x.setDesde(dateDesde.getDate());
                x.setHasta(dateHasta.getDate());
                x.setObjeto(Long.valueOf(textElemento.getText()));
                x.setTipo(Integer.valueOf(tipo[0]));
                
                if(id>0)
                    y.update(x);
                else
                    y.save(x);

                dispose();
                FormOfertas.jButtonBuscar.doClick();
            }else{
                JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios.");
            }
//        }else{
//            JOptionPane.showMessageDialog(null, "Los passwords deben coincidir.");
//        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void textElementoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textElementoKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_F5) {
            String[] tipo = comboTipo.getSelectedItem().toString().split("-");
            switch(Integer.valueOf(tipo[0])){
                case 1:  
                    ListaProductos listaProductos = new ListaProductos(); 
                    listaProductos.setVisible(true);
                    textElemento.setText(listaProductos.getSeleccionado());
                    textElementoNombre.setText(listaProductos.getSeleccionadoNombre());
                    break;
                case 2: 
                    ListaFamilias listaFamilias = new ListaFamilias(); 
                    listaFamilias.setVisible(true);
                    textElemento.setText(listaFamilias.getSeleccionado());
                    textElementoNombre.setText(listaFamilias.getSeleccionadoNombre());
                    break;
                case 3: 
                    ListaSubfamilias listaSubfamilias = new ListaSubfamilias(); 
                    listaSubfamilias.setVisible(true);
                    textElemento.setText(listaSubfamilias.getSeleccionado());
                    textElementoNombre.setText(listaSubfamilias.getSeleccionadoNombre());
                    break;
                case 4:  
                    ListaUbicaciones listaUbicaciones = new ListaUbicaciones(); 
                    listaUbicaciones.setVisible(true);
                    textElemento.setText(listaUbicaciones.getSeleccionado());
                    textElementoNombre.setText(listaUbicaciones.getSeleccionadoNombre());
                    break;
                default: 
                    break;
            }    
        }
    }//GEN-LAST:event_textElementoKeyPressed

    private void comboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoItemStateChanged
        // TODO add your handling code here:
        textElemento.setText("");
        textElementoNombre.setText("");
        textElemento.requestFocus();
    }//GEN-LAST:event_comboTipoItemStateChanged

    private void textElementoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textElementoFocusLost
        // TODO add your handling code here:
        String[] tipo = comboTipo.getSelectedItem().toString().split("-");
        switch(Integer.valueOf(tipo[0])){
            case 1:  
                Producto p = productoRepo.get(Long.valueOf(textElemento.getText()));
                textElementoNombre.setText(p.getNombre());
                break;
            case 2: 
                Familia f = familiaRepo.get(Long.valueOf(textElemento.getText()));
                textElementoNombre.setText(f.getNombre());
                break;
            case 3: 
                Subfamilia s = subfamiliaRepo.get(Long.valueOf(textElemento.getText()));
                textElementoNombre.setText(s.getNombre());
                break;
            case 4:  
                Ubicacion u = ubicacionRepo.get(Long.valueOf(textElemento.getText()));
                textElementoNombre.setText(u.getNombre());
                break;
            default: 
                break;
        }    
    }//GEN-LAST:event_textElementoFocusLost

    private void cargarValores(){
               
        x = y.get(this.id);
        textElementoNombre.setText(id.toString());
        textNombre.setText(x.getNombre());
         //SETEO FECHA ACTUAL
        dateDesde.setDate(x.getDesde());
        dateHasta.setDate(x.getHasta());
        
        String nombre = "";
        switch(x.getTipo()){
            case 1:  nombre = "Producto";
                     break;
            case 2:  nombre = "Familia";
                     break;
            case 3:  nombre = "Subfamilia";
                     break;
            case 4:  nombre = "Ubicacion";
                     break;
            default: nombre = "";
                     break;
        }    
        comboTipo.setSelectedItem(x.getTipo()+"-"+nombre);
        textDescuento.setText(x.getDescuento()+"");
        
        //SETEA ELEMENTO
        textElemento.setText(x.getObjeto()+"");
        String elemento = "";
        switch(x.getTipo()){
            case 1:  
                producto = productoRepo.get(x.getObjeto());
                elemento = producto.getNombre();
                break;
            case 2:  
                familia = familiaRepo.get(x.getObjeto());
                elemento = familia.getNombre();
                break;
            case 3:  
                subfamilia = subfamiliaRepo.get(x.getObjeto());
                elemento = subfamilia.getNombre();
                break;
            case 4:  
                ubicacion = ubicacionRepo.get(x.getObjeto());
                elemento = ubicacion.getNombre();
                break;
            default: elemento = "";
                break;
        }
        textElementoNombre.setText(elemento);
        
        repaint();
        revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboTipo;
    private org.jdesktop.swingx.JXDatePicker dateDesde;
    private org.jdesktop.swingx.JXDatePicker dateHasta;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JFormattedTextField textDescuento;
    private javax.swing.JFormattedTextField textElemento;
    private javax.swing.JTextField textElementoNombre;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
